baseURL = "https://withong.github.io/"
languageCode = "ko-kr"
title = "withong"
theme = "papermod"
defaultTheme = "auto"
relativeURLs = true
uglyURLs = false

[taxonomies]
  category = "topic"
  tag = "tag"

[params]
  title = "withong"
  description = "Today I Learned"
  dateFormat = "January 2, 2006"
  mainsections = ["camp", "java", "topic", "tag", "search"]

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"
disableFingerprinting = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 2
  limit = 10
  keys = ["title", "content", "topic", "tags"]

[params.profileMode]
  enabled = true
  title = "rang's log" # 사이트 제목 (기본값: 사이트 타이틀)
  subtitle = "Today I Learned" # 부제목
  imageUrl = "https://raw.githubusercontent.com/withong/sparta/main/zep_profile_250x250.png" # 프로필 사진 URL
  imageTitle = "zep" # 이미지 설명 (alt 속성)
  imageWidth = 120 # 프로필 이미지 너비
  imageHeight = 120 # 프로필 이미지 높이

# [[params.profileMode.buttons]]
#  name = "Home"
#  url = "/"

[[params.profileMode.buttons]]
  name = "GitHub"
  url = "https://github.com/withong"

[params.homeInfoParams]
Title = "rang's log"
Content = "Today I Learned ✏️"

[pagination]
  pagerSize = 5

[menu]

[[menu.main]]
  identifier = "Log"
  name = "Log" # 실제 화면에 보이는 이름
  url = "/log/"
  weight = 5

[[menu.main]]
  identifier = "topic"
  name = "Topic"
  url = "/topic/"
  weight = 10

[[menu.main]]
  identifier = "tag"
  name = "Tag"
  url = "/tag/"
  weight = 15

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 20

[outputs]
  home = ["HTML", "JSON"]
