baseURL = "https://withong.github.io/"
languageCode = "ko-kr"
title = "withong"
theme = "papermod"
defaultTheme = "auto"
relativeURLs = true
uglyURLs = false

[taxonomies]
  category = "topic"
  tag = "tag"

[params]
  title = "withong"
  description = "Today I Learned"
  dateFormat = "January 2, 2006"
  mainsections = ["camp", "java", "topic", "tag", "search"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 2
  limit = 10
  keys = ["title", "content", "topic", "tags"]

[params.homeInfoParams]
Title = "rang's log"
Content = "Today I Learned ✏️"


[pagination]
  pagerSize = 5

[menu]

[[menu.main]]
  identifier = "log"
  name = "log"
  url = "/log/"
  weight = 5

[[menu.main]]
  identifier = "topic"
  name = "topic"
  url = "/topic/"
  weight = 10

[[menu.main]]
  identifier = "tag"
  name = "tag"
  url = "/tag/"
  weight = 15

[[menu.main]]
  identifier = "search"
  name = "search"
  url = "/search/"
  weight = 20

[outputs]
  home = ["HTML", "JSON"]
