baseURL = "https://withong.github.io/"
relativeURLs = false
canonifyURLs = true
languageCode = "ko"
defaultContentLanguage = "ko"
title = "withong"
theme = "papermod"
disableThemeToggle = true
defaultTheme = "auto"
uglyURLs = false
pygmentsUseClasses = true
publishDir = "docs"

[taxonomies]
  tag = "tag"
# category = "topic"

[params]
  title = "withong"
  description = "Today I Learned"
  dateFormat = "2006년 1월 2일"
  mainsections = ["record", "project", "tag", "search"]
  ShowPostNavLinks = true
  UseHugoToc = true
  showtoc = true
  tocopen = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableLiveReload = true

[params.assets]
  disableFingerprinting = true
  favicon = "/icons/rec.png"
  favicon16x16 = "/icons/rec.png"
  favicon32x32 = "/icons/rec.png"
  apple_touch_icon = "/icons/rec.png"
  safari_pinned_tab = "/icons/rec.png"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 100
  threshold = 0.2
  minMatchCharLength = 2
  limit = 10
  keys = ["title", "content", "topic", "tag"]

[params.profileMode]
  enabled = true
  title = "rang's log" # 사이트 제목 (기본값: 사이트 타이틀)
  subtitle = "Today I Learned" # 부제목
  imageUrl = "https://raw.githubusercontent.com/withong/my-storage/main/zep_profile_rmbg.png" # 프로필 사진 URL
  imageTitle = "zep" # 이미지 설명 (alt 속성)
  imageWidth = 150 # 프로필 이미지 너비
  imageHeight = 150 # 프로필 이미지 높이

# [[params.profileMode.buttons]]
#  name = "Home"
#  url = "/"

[[params.profileMode.buttons]]
  name = "GitHub"
  url = "https://github.com/withong"

[params.homeInfoParams]
Title = "rang's log"
Content = "Today I Learned ✏️"

[pagination]
  pagerSize = 10

[menu]

[[menu.main]]
  identifier = "Log"
  name = "☰" # 메뉴바에 보이는 이름
  url = "/log/"
  weight = 5

[[menu.main]]
  identifier = "record"
  name = "Record" # 메뉴바에 보이는 이름
  url = "/record/"
  weight = 10

[[menu.main]]
  identifier = "project"
  name = "Project" # 메뉴바에 보이는 이름
  url = "/project/"
  weight = 15

[[menu.main]]
  identifier = "tag"
  name = "Tag" # 메뉴바에 보이는 이름
  url = "/tag/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search" # 메뉴바에 보이는 이름
  url = "/search/"
  weight = 25

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
  [markup.tableOfContents]
    startLevel = 2 # ##부터 목차에 포함 (#은 보통 문서 제목이라 생략)
    endLevel = 3 # ###까지 포함
    ordered = false # 번호 없는 리스트로 표시

  [markup.highlight]
    noClasses = false
